version: '3'

dotenv: [".env"]

env:
  BACKUP_NAME:
    sh: "echo backup-$(date +'%Y-%m-%d-%H-%M-%S').7z"

tasks:
  nginx-vhosts:
    internal: true
    vars:
      INCLUDE_DIRS: "/etc/nginx/sites-enabled/"
      EXCLUDE_DIRS: "/etc/nginx/sites-enabled/default"
    cmds:
      - task: compress
        vars:
          INCLUDE_DIRS: '{{ .INCLUDE_DIRS }}'
          EXCLUDE_DIRS: '{{ .EXCLUDE_DIRS }}'
    status:
      - |
        ls {{ .INCLUDE_DIRS }} | grep -q . && exit 1 || exit 0

  mysql-dump:
    internal: true
    cmds:
      - cmd: mysqldump --user={{ .MYSQL_USERNAME }} --password={{ .MYSQL_PASSWORD }} --databases {{ .MYSQL_DATABASES }} --skip-add-locks --no-tablespaces > {{ .BACKUP_PATH }}/mysql-dump.sql
      - task: compress
        vars:
          INCLUDE_DIRS: "$BACKUP_PATH/mysql-dump.sql"
    status:
      - | 
        {{ if gt .MYSQL_DATABASES "" }}exit 1{{ else }}exit 0{{ end }}

  mongodb-dump:
    internal: true
    cmds:
      - for: { var: MONGODB_DATABASES, split: ',' }
        task: mongodb-dump-db
        vars:
          MONGODB_DATABASE: "{{ .ITEM }}"
      - task: compress
        vars:
          INCLUDE_DIRS: "$BACKUP_PATH/mongodb-dump"
    status:
      - |
        {{ if gt .MONGODB_DATABASES "" }}exit 1{{ else }}exit 0{{ end }}

  mongodb-dump-db:
    cmds:
      - cmd: mongodump --username={{ .MONGODB_USERNAME }} --password={{ .MONGODB_PASSWORD }} --authenticationDatabase={{ .MONGODB_AUTH_DB }} --db={{ .MONGODB_DATABASE }} --out {{ .BACKUP_PATH }}/mongodb-dump
      - task: compress
        vars:
          INCLUDE_DIRS: "$BACKUP_PATH/mongodb-dump"

  cleanup: rm -rf $BACKUP_PATH

  compress:
    internal: true
    cmds:
      - cmd: |
          {{ .COMPRESSION_7Z_PATH }} a -t7z -m0=lzma -mx={{ .COMPRESSION_LEVEL }}  -mmt1 -ms=on -mhe -p"{{ .COMPRESSION_PASSWORD }}" {{ .BACKUP_PATH }}/{{ .BACKUP_NAME }}.7z {{ range $i, $dir := splitList "," .INCLUDE_DIRS }}{{ $dir }} {{ end }} {{ range $i, $dir := splitList "," .EXCLUDE_DIRS }}-xr!{{ $dir }} {{ end }}

  run:
    cmds:
      - cmd: |
          echo "Creating backup file: $BACKUP_NAME in $BACKUP_PATH"
#      - task: cleanup
      - cmd: mkdir -p $BACKUP_PATH
#      - defer: { task: cleanup }
      - task: nginx-vhosts
      - task: mysql-dump
      - task: mongodb-dump
