version: '3'

dotenv: [".env.{{ .CONFIG }}", ".env.dist"]

env:
  BACKUP_NAME:
    sh: "echo backup-$(date +'%Y-%m-%d-%H-%M-%S').7z"

tasks:
  directories:
    internal: true
    vars:
      INCLUDE_DIRS: "{{ .BACKUP_INCLUDE_DIRS }}"
      EXCLUDE_DIRS: "{{ .BACKUP_EXCLUDE_DIRS }}"
    cmds:
      - task: compress
    status:
      - |
        ls {{ .INCLUDE_DIRS }} | grep -q . && exit 1 || exit 0

  nginx-vhosts:
    internal: true
    vars:
      INCLUDE_DIRS: "/etc/nginx/sites-enabled/"
      EXCLUDE_DIRS: "/etc/nginx/sites-enabled/default"
    cmds:
      - task: compress
        vars:
          INCLUDE_DIRS: '{{ .INCLUDE_DIRS }}'
          EXCLUDE_DIRS: '{{ .EXCLUDE_DIRS }}'
    status:
      - |
        ls {{ .INCLUDE_DIRS }} | grep -q . && exit 1 || exit 0

  mysql-dump:
    internal: true
    cmds:
      - cmd: mysqldump --user={{ .MYSQL_USERNAME }} --password={{ .MYSQL_PASSWORD }} --databases {{ .MYSQL_DATABASES }} --skip-add-locks --no-tablespaces > {{ .BACKUP_WORK_DIRECTORY }}/mysql-dump.sql
      - task: compress
        vars:
          INCLUDE_DIRS: "{{ .BACKUP_WORK_DIRECTORY }}/mysql-dump.sql"
          EXCLUDE_DIRS: ""
    status:
      - | 
        {{ if gt .MYSQL_DATABASES "" }}exit 1{{ else }}exit 0{{ end }}

  mongodb-dump:
    internal: true
    cmds:
      - for: { var: MONGODB_DATABASES, split: ',' }
        task: mongodb-dump-db
        vars:
          MONGODB_DATABASE: "{{ .ITEM }}"
      - task: compress
        vars:
          INCLUDE_DIRS: "{{ .BACKUP_WORK_DIRECTORY }}/mongodb-dump"
          EXCLUDE_DIRS: ""
    status:
      - |
        {{ if gt .MONGODB_DATABASES "" }}exit 1{{ else }}exit 0{{ end }}

  mongodb-dump-db:
    internal: true
    cmds:
      - cmd: mongodump --username={{ .MONGODB_USERNAME }} --password={{ .MONGODB_PASSWORD }} --authenticationDatabase={{ .MONGODB_AUTH_DB }} --db={{ .MONGODB_DATABASE }} --out {{ .BACKUP_WORK_DIRECTORY }}/mongodb-dump
      - task: compress
        vars:
          INCLUDE_DIRS: "{{ .BACKUP_WORK_DIRECTORY }}/mongodb-dump"
          EXCLUDE_DIRS: ""

  cleanup: rm -rf {{ .BACKUP_WORK_DIRECTORY }}

  compress:
    internal: true
    cmds:
      - cmd: |
          {{ .COMPRESSION_7Z_PATH }} a -t7z -m0=lzma -mx={{ .COMPRESSION_LEVEL }}  -mmt1 -ms=on -mhe -p"{{ .COMPRESSION_PASSWORD }}" {{ .BACKUP_WORK_DIRECTORY }}/{{ .BACKUP_NAME }}.7z {{ range $i, $dir := splitList "," .INCLUDE_DIRS }}{{ $dir }} {{ end }} {{ if gt .EXCLUDE_DIRS "" }}{{ range $i, $dir := splitList "," .EXCLUDE_DIRS }}-xr!{{ $dir }} {{ end }}{{ end }}

  upload:
    internal: true
    cmds:
      - cmd: |
          {{ .RCLONE_PATH }} copy {{ .BACKUP_WORK_DIRECTORY }}/{{ .BACKUP_NAME }}.7z {{ .RCLONE_REMOTE }}:{{ .RCLONE_DESTINATION }}/{{ .BACKUP_NAME }}.7z

  delete-old-backups:
    cmds:
      - cmd: |
          {{ .RCLONE_PATH }} delete --min-age={{ .BACKUP_RETENTION }} {{ .RCLONE_REMOTE }}:{{ .RCLONE_DESTINATION }}
    status:
      - |
        {{ if gt .BACKUP_RETENTION "" }}exit 1{{ else }}exit 0{{ end }}

  run:
    cmds:
      - cmd: |
          echo "Creating backup file: {{ .BACKUP_NAME }} in {{ .BACKUP_WORK_DIRECTORY }}"
#      - task: cleanup
      - cmd: mkdir -p {{ .BACKUP_WORK_DIRECTORY }}
#      - defer: { task: cleanup }
      - task: directories
      - task: nginx-vhosts
      - task: mysql-dump
      - task: mongodb-dump
      - task: upload
      - task: delete-old-backups
